import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Reis Çelik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-4`}>
        {children}
        <footer>
          <p className="text-left text-sm leading-3 ml-2 text-zinc-600">
            Design by{" "}
            <Link
              className="leading-3 line-through"
              href={"https://github.com/JeppeHauman"}
            >
              J
            </Link>{" "}
            &{" "}
            <Link
              className="leading-3 line-through"
              href={"https://github.com/n13a"}
            >
              N
            </Link>
          </p>
        </footer>
      </body>
    </html>
  );
}
