import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from './components/footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Reis Çelik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-2 md:px-4`}>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
